import React, { useState } from 'react';
import CardOption from '../../../../components/CardOption';

const IdeaInspirePage = () => {
  const [step, setStep] = useState(1);
  const [isCreateCaption, setIsCreateCaption] = useState(false);

  const handleSelectIdea = () => {
    setStep(2);
    // TODO: CALL API TO GENERATE IDEA AND SET SELECTED IDEA
  };

  const handleCreateCaption = () => {
    setIsCreateCaption(true);
    // TODO: CALL API TO CREATE CAPTION
  };

  return (
    <div className='flex-1 p-20'>
      {step === 1 && (
        <>
          <div className='w-[430px]'>
            <h1 className='font-bold text-2xl'>Get Inspried</h1>
            <p className='mt-10 mb-3 font-semibold'>Choose an idea to build some posts</p>
          </div>
          <div className='w-[430px]'>
            <h1 className='font-bold text-2xl mb-3'>Your Idea</h1>
            <div
              className='border rounded-md border-gray-300 py-4 px-2 mb-3 hover:bg-gray-50 cursor-pointer'
              onClick={handleSelectIdea}
            >
              Idea generated by AI 1
            </div>
            <div className='border rounded-md border-gray-300 py-4 px-2 mb-3 hover:bg-gray-50 cursor-pointer'>
              Idea generated by AI 2
            </div>
          </div>
        </>
      )}

      {step === 2 && (
        <>
          <h2 className='font-bold text-2xl mb-3'>Your Idea</h2>
          <div className='border rounded-md border-gray-300 py-4 px-2 mb-3 hover:bg-gray-50 cursor-pointer'>
            Idea generated by AI 2
          </div>
          <div className='flex justify-end my-2'>
            <button className='py-3 px-6 bg-[#E8EDFF] rounded-md hover:opacity-90' onClick={handleCreateCaption}>
              Create caption
            </button>
          </div>
          {isCreateCaption && (
            <>
              <h2 className='font-bold text-2xl mb-3'>Captions created for you</h2>
              <CardOption
                content='Introducing Skipli AI - the smarter, faster way to craft
compelling content  Experience all the magic of
 Al-driven wriing assistant and get great results
with fewer headaches.#AI #ContentMarketing #Content'
              />
            </>
          )}
        </>
      )}
    </div>
  );
};

export default IdeaInspirePage;
